server:
  port: 8081

spring:
  application:
    name: acl-service
  datasource:
    url: jdbc:postgresql://localhost:5432/zanzibar
    username: zanzibar
    password: zanzibar
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "event:dev.zanzibar.events.PermissionChangeEvent"
