server:
  port: 8082

spring:
  application:
    name: leopard-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: leopard-indexer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.zanzibar.events"
        spring.json.value.default.type: "dev.zanzibar.events.PermissionChangeEvent"
